[[CURRENCIES]]
code = "ST"
issuer = "GDMFRY7PWOU3ECBEP3VDV6ZTGAQ3D3DJFJMTH5BYIPGREPF6ZB2ZK3BM"
display_decimals = 7
name = "StellarNet Token"
desc = "Utility token for the first onchain mobile service – fee discounts, rewards, governance"
image = https://editor.mywebsite-now.com/-_-/res/280fd9ef-6e95-4de3-9226-9907e58de7cd/images/files/280fd9ef-6e95-4de3-9226-9907e58de7cd/6f6ccdb4-6f2d-46e0-b756-3035f553d9ec/192-192/5a140e8fb24f5169e6b4af78684d397f4b5ee8a3?o=width:192/height:192/
